
trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - /CI-CD-Setup
name: $(Date:yyyyMMdd)$(Rev:.r)_
variables:
- group: Deployment - SharePoint Environment
jobs:
- job: Job_1
  displayName: SPFx Package Building Agent
  pool:
    vmImage: ubuntu-20.04
  steps:
  - checkout: self
  - task: NodeTool@0
    displayName: Install Node 14.15.0
    inputs:
      versionSpec: 14.15.0
  - task: Npm@1
    displayName: npm install
    inputs:
      workingDir: PDPApp
      verbose: false
  - task: gulp@0
    displayName: SPFx - Bundle Solution
    inputs:
      gulpFile: $(ProjectFolder)/gulpfile.js
      targets: bundle
      arguments: --ship
      cwd: $(ProjectFolder)
  - task: gulp@0
    displayName: SPFx - Ship the solution
    inputs:
      gulpFile: $(ProjectFolder)/gulpfile.js
      targets: package-solution
      arguments: --ship
      cwd: $(ProjectFolder)
  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)/$(ProjectFolder)/drop'
    inputs:
      SourceFolder: $(ProjectFolder)
      Contents: $(SolutionPackageLocation)/$(PackageName)
      TargetFolder: $(build.artifactstagingdirectory)/$(ProjectFolder)/drop
  - task: CopyFiles@2
    displayName: 'Copy Script Files to: $(build.artifactstagingdirectory)/$(ProjectFolder)/drop'
    inputs:
      SourceFolder: CI-CD-Setup/scripts-powershell
      Contents: '*'
      TargetFolder: $(build.artifactstagingdirectory)/$(ProjectFolder)/drop
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)/$(ProjectFolder)/drop